lupus/urls.py
#from django.conf.urls import patterns, url, include
from django.conf.urls import url, include

from lupus import views
from lupus import gmviews
#from lupus import appviews

app_name = "lupus"

gm_patterns = [
	#SEZIONE GM
	url(r"^$", gmviews.GMView.as_view(), name="gm_index"),
	url(r"^(?P<id>\d+)$", gmviews.GMView.as_view(), name="gm_index_single"),
	#GESTIONE RUOLI
	url(r"^ruoli/(?P<match_id>\d*)$", gmviews.GMRolesView.as_view(), name="gm_assegnazione_ruoli"),
	url(r"^ruoli/users$", gmviews.gm_user_match, name="gm_user_match"),
	url(r"^ruoli/set$", gmviews.gm_set_role, name="gm_set_user_role"),
	url(r"^ruoli/setusers$", gmviews.gm_set_users_role, name="gm_set_users_role"),
	url(r"^ruoli/set/random$", gmviews.gm_set_role_random, name="gm_set_user_role_random"),
	#GESTIONE EVENTI
	url(r"^eventi/(?P<match_id>\d*)$", gmviews.GMEventsView.as_view(), name="gm_gestione_eventi"),
	url(r"^eventi/modifica$", gmviews.gm_edit_event, name="gm_modifica_evento"),
	url(r"^eventi/elimina$", gmviews.gm_del_event, name="gm_elimina_eveto"),
	url(r"^eventi/add", gmviews.gm_add_event, name="gm_aggiungi_evento"),
	#GESTIONE NOTE
	url(r"^note/(?P<match_id>\d*)$", gmviews.GMNotaView.as_view(), name="gm_gestione_note"),
	url(r"^note/modifica$", gmviews.gm_edit_nota, name="gm_modifica_nota"),
	url(r"^note/elimina$", gmviews.gm_del_nota, name="gm_elimina_nota"),
	url(r"^note/add", gmviews.gm_add_nota, name="gm_aggiungi_nota"),
	#GESTIONE AZIONI
	url(r"^azioni/(?P<match_id>\d*)$", gmviews.GMActionView.as_view(), name="gm_gestione_azioni"),
	url(r"^azioni/modifica$", gmviews.gm_edit_action, name="gm_modifica_azione"),
	url(r"^azioni/elimina$", gmviews.gm_del_action, name="gm_elimina_azione"),
	url(r"^azioni/add", gmviews.gm_add_action, name="gm_aggiungi_azione"),
	#GESTIONE STATI
	url(r"^status/(?P<match_id>\d*)$", gmviews.GMStatusView.as_view(), name="gm_gestione_status"),
	url(r"^status/modifica$", gmviews.gm_edit_status, name="gm_modifica_status"),
	url(r"^status/clear$", gmviews.gm_clear_status, name="gm_pulizia_status"),
	url(r"^status/random$", gmviews.gm_status_random, name="gm_assegnamento_status_random"),
	#GESTIONE GRUPPI
	url(r"^gruppi$", gmviews.GMGroupsView.as_view(), name="gm_gestione_gruppi"),
	url(r"^gruppi/add$", gmviews.gm_add_group, name="gm_aggiungi_gruppo"),
	url(r"^gruppi/edit$", gmviews.gm_edit_group, name="gm_modifica_gruppo"),
	url(r"^gruppi/del$", gmviews.gm_del_group, name="gm_elimina_gruppo"),
	#GESTIONE MATCH
	url(r"^match$", gmviews.GMMatchView.as_view(), name="gm_gestione_match"),
	url(r"^match/add$", gmviews.gm_add_match, name="gm_aggiungi_match"),
	url(r"^match/edit$", gmviews.gm_edit_match, name="gm_modifica_match"),
	url(r"^match/del$", gmviews.gm_del_match, name="gm_elimina_match"),
	url(r"^match/deactivate$", gmviews.gm_deactivate_users_match, name="gm_disattiva_utenti_match"),
	#GESTIONE VOTAZIONI
	url(r"^votazioni/(?P<match_id>\d*)$", gmviews.GMVotiView.as_view(), name="gm_gestione_voti"),
	url(r"^votazioni/modifica$", gmviews.gm_edit_voto, name="gm_modifica_voto"),
	url(r"^votazioni/elimina$", gmviews.gm_del_voto, name="gm_elimina_voto"),
	url(r"^votazioni/add$", gmviews.gm_add_voto, name="gm_aggiungi_voto"),
	#GESTIONE NOTTE E LINCIAGGIO
	url(r"^notte/(?P<match_id>\d*)$", gmviews.GMValView.as_view(), name="gm_gestione_notte", kwargs={"flags": 2}),
	url(r"^notte/confirm$", gmviews.GMValConfirmView.as_view(), name="gm_conferma_notte"),
	url(r"^notte/do$", gmviews.GMValDoPostView.as_view(), name="gm_esegui_notte"),
	#url(r"^notte/do$", gmviews.gm_val_do, name="gm_esegui_notte"),
	url(r"^linciaggio/(?P<match_id>\d*)$", gmviews.GMValView.as_view(), name="gm_linciaggio", kwargs={"flags": 1}),
	url(r"^linciaggio/confirm$", gmviews.GMValConfirmView.as_view(), name="gm_conferma_linciaggio"),
	url(r"^linciaggio/do$", gmviews.GMValDoPostView.as_view(), name="gm_esegui_linciaggio"),
	#url(r"^linciaggio/do$", gmviews.gm_val_do, name="gm_esegui_linciaggio"),
	#CAMBIO PROFILO
	url(r"^profile$", gmviews.GMChangeProfileView.as_view(), name="gm_setprofile"),
	#GESTIONE FINE MATCH
	url(r"^end/(?P<match_id>\d*)$", gmviews.GMEndMatch.as_view(), name="gm_end_match"),
	#GESTIONE GM
	url(r"^staff$", gmviews.GMStaffView.as_view(), name="gm_staff"),
	url(r"^staff/add$", gmviews.gm_add_staff, name="gm_staff_add"),
	url(r"^su/add$", gmviews.gm_add_su, name="gm_su_add"),
	url(r"^su/del/(?P<id>\d+)$", gmviews.gm_del_su, name="gm_su_elimina"),
	#GESTIONE ISCRITTI
	url(r"^iscritti/(?P<match_id>\d+)$", gmviews.GMIscrittiView.as_view(), name="gm_gestione_iscritti"),
	url(r"^iscritti/edit$", gmviews.gm_edit_iscritto, name="gm_modifica_iscritto"),
	url(r"^iscritti/del$", gmviews.gm_del_iscritto, name="gm_elimina_iscritto")
]



urlpatterns = [
	# INDICE E GIORNALE
	url(r"^$", views.Index.as_view(), name ="index"),
	url(r"^index$", views.Index.as_view()),
	url(r"^giornale(?P<match_id>\d+)$", views.GiornaleView.as_view(), name="giornale"),
	url(r"^giornale/pdf(?P<match_id>\d+)$", views.notImplemented.as_view(), name ="giornale_pdf"),
	# REGOLAMENTO
	url(r"^regolamento$", views.RegView.as_view(), name ="regolamento"),
	url(r"^regolamento/online$", views.RegOnlineView.as_view(), name ="regolamento_online"),
	# GESTIONE MATCH
	url(r"^game$", views.GameView.as_view(), name ="gioco"),
	url(r"^game/leave$", views.GameLeaveView.as_view(), name ="gioco_leave"),
	url(r"^game/askleave$", views.GameAskLeaveView.as_view(), name ="gioco_askleave"),
	# GESTIONE PROFILO
	url(r"^profile$", views.ProfileView.as_view(), name ="profile"),
	url(r"^profile/make$", views.ProfileMakeView.as_view(), name ="profile_make"),
	url(r"^profile/(?P<user_id>\d+)$", views.ProfileOtherView.as_view(), name="profile_other"),
	# RIASSUNTO STATUS
	url(r"^status$", views.StatusView.as_view(), name ="status"),
	url(r"^status/postaction$", views.StatusActionView.as_view(), name ="status_action"),
	# VILLAGGIO E VOTAZIONI
	url(r"^villaggio/pastsindaco", views.VotazioniPassateSindacoView.as_view(), name ="villaggio_pastsindaco"),
	url(r"^villaggio/past", views.VotazioniPassateView.as_view(), name ="villaggio_past"),
	#url(r"^villaggio/postvoto(?P<flag_id>\d{1})_(?P<utente_id>\d+)$", views.VillaggioPostVotoView.as_view(), name ="villaggio_postvoto"),
	url(r"^villaggio/postvoto$", views.VillaggioPostFormVotoView.as_view(), name ="villaggio_postvoto"),
	url(r"^villaggio", views.VillaggioView.as_view(), name ="villaggio"),
	# PROPRIO GRUPPO E AZIONI NOTTURNE
	url(r"^gruppo$", views.GruppoView.as_view(), name ="gruppo"),
	url(r"^gruppo/azione$", views.GruppoAzioneView.as_view(), name ="gruppo_azione"),
	# CHAT DI GRUPPO
	url(r"^gruppo/postmsg$", views.gruppo_postmsg, name ="gruppo_postmsg"),
	url(r"^gruppo/getmsg(?P<isvillaggio>\d{1})_(?P<first_id>\d+)to(?P<last_id>\d+)$", views.gruppo_getmsg, name ="gruppo_getmsg"),
	# RIASSUNTO
	url(r"^summary$", views.SummaryCurrentView.as_view(), name ="summary_current"),
	url(r"^summary/match(?P<match_id>\d+)$", views.SummaryView.as_view(), name ="summary"),
	url(r"^summary/history(?P<match_id>\d+)$", views.SummaryFullView.as_view(), name ="summary_full"),
	url(r"^summary/pdf(?P<match_id>\d+)$", views.notImplemented.as_view(), name ="summary_pdf"),
	
	url(r"^IE.html$", views.IEwarningView.as_view(), name="IEwarning"),
	
	# GAME MASTER
	url(r'^gm/', include((gm_patterns,""))),
	
	# PROCEDURE AUTOMATICHE
	url(r'^auto/', include(
		([
			url(r"^giorno_all$", views.esegui_giorno_all_view, name ="giorno_all"),
			url(r"^notte_all$", views.esegui_notte_all_view, name ="notte_all"),
			url(r"^vittoria_all$", views.esegui_vittoria_all_view, name ="vittoria_all")
		],"auto")
	,namespace="auto")),
]

lupusrealtime/urls.py
from django.conf.urls import include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = [
    # Examples:
    # url(r'^$', 'lupusrealtime.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^', include('lupus.urls', namespace="lupus")),
    url(r'^auth/', include("mylogin.urls", namespace="login")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
]

mylogin/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from mylogin import views

app_name = "login"

urlpatterns = [
	url(r"^$", views.index, name ="index"),
	url(r"^login/$", views.login, name ="login"),
	url(r"^logout/$", views.logout, name ="logout"),
	url(r"^dologin/$", views.login_form, name ="dologin"),
	url(r"^signup/$", views.signup, name ="signup"),
	url(r"^check/$", views.signup_check, name ="signup_check"),
	url(r"^password/reset$", auth_views.password_reset, {"template_name": "mylogin/password_reset.html", "password_reset_form": views.MyPasswordResetForm, "post_reset_redirect": "login:password_reset_done"}, name="password_reset"),
	url(r"^password/reset/sent$", auth_views.password_reset_done, {"template_name": "mylogin/password_reset_done.html"}, name="password_reset_done"),
	url(r"^password/reset/confirm/uid=(?P<uidb64>[0-9A-Za-z_\-]+)&token=(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})$", auth_views.password_reset_confirm, {"template_name": "mylogin/password_reset_confirm.html", "post_reset_redirect": "login:password_reset_complete"}, name="password_reset_confirm"),
	url(r"^password/reset/done$", auth_views.password_reset_complete, {"template_name": "mylogin/password_reset_complete.html"}, name="password_reset_complete"),
	url(r"^password/change$", auth_views.password_change, {"template_name": "mylogin/password_change.html", "post_change_redirect": "login:password_change_done"}, name="password_change"),
	url(r"password/change/done$", auth_views.password_change_done, {"template_name": "mylogin/password_change_done.html"}, name="password_change_done"),
]

mylogin/views.py
# -*- encoding: utf8 -*-
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.urls import reverse
from django.utils.http import urlencode

from django.contrib import messages
from django.contrib.auth import login as django_login, logout as django_logout
from django.contrib.auth.models import User

from django.contrib.auth.forms import *
#from django import forms

from django.utils import timezone

from .models import UserVerificationKey

from django.core.mail import EmailMessage, send_mail

MAX_UNCHECKED_USER_X_IP = 5
MIN_PASSWORD_LENGTH = 4
CLEAN_OLD_KEYS = False

ALLOW_WITHOUT_EMAIL = False
EMAIL_SENDER_ADDRESS = "lupusrealtime@gmx.com"
EMAIL_PREFIX = "[LRT] "

class MyUserCreationForm(UserCreationForm):
	class Meta(UserCreationForm.Meta):
		fields = UserCreationForm.Meta.fields + ("first_name","last_name", "email")
	def clean(self):
		cleaned_data = super(MyUserCreationForm, self).clean()
		first_name = cleaned_data.get("first_name")
		last_name = cleaned_data.get("last_name")
		if (not first_name) and (not last_name):
			raise forms.ValidationError("E' riesco almeno un campo fra nome e cognome")
		password = cleaned_data.get("password1")
		if (password) :
			if (password.isalnum() or password.isalpha() or password.isdigit()) :
				del cleaned_data["password1"]
				raise forms.ValidationError("Scegli un password con lettere, numeri e caratteri speciali")
			if (len(password) < MIN_PASSWORD_LENGTH) :
				del cleaned_data["password1"]
				raise forms.ValidationError("Scegli un password di almeno %(min_length)d caratteri", params={"min_length":MIN_PASSWORD_LENGTH})
		email = cleaned_data.get("email")
		if (not email):
			raise forms.ValidationError("E' richiesto un indirizzo email valido")
		else :
			if User.objects.filter(email=email).exists() :
				raise forms.ValidationError("Indirizzo email non valido")
		return cleaned_data

PASSWORD_RESET_EMAIL_FORMAT = """
<h3>Richiesta reset password per <b>%(user)s</b></h3>
<p>Questa email &egrave; stata fornita per richiedere il reset della password del prorpio account sul sito <i>%(site_name)s</i>.</p>
<p>Apri il link seguente per scegliere una nuova password: <br>
<a href="%(url)s"> [<small> %(url)s </small>] </a></p><br>
<p>Se non sei tu ad aver richiesto la reimpostazione della password cancella pure questa email.</p><br>
<p><small>Email generata automaticamente da Django. Non rispondere.</small></p>
"""

class MyPasswordResetForm(PasswordResetForm):
	def send_mail(self, subject_template_name, email_template_name, context, from_email, to_email, html_email_template_name=None):
		"""
		Invia la mai per il reset della password
		"""
		subject = EMAIL_PREFIX + "Richiesta reset password"
		url = "https://" + context["domain"] + reverse("login:password_reset_confirm", kwargs={"uidb64": context["uid"], "token": context["token"]})
		context["url"] = url
		content = PASSWORD_RESET_EMAIL_FORMAT%context
		msg = EmailMessage( subject, content, EMAIL_SENDER_ADDRESS, to=[to_email], bcc=[EMAIL_SENDER_ADDRESS])
		msg.content_subtype = "html"
		msg.send()

def index(request):
	return render(request,"mylogin/index.html",{})

VERIFICATION_EMAIL_FORMAT = """
<h3>Verifica dell'account <b>%(username)s</b></h3>
<p>Questa email &egrave; stata fornita per registrare un account sul sito <i>%(host)s</i>.</p>
<p>Il codice di verifica dell'account e' <b>%(key)s</b><br>Apri il link seguente per attivare il tuo utente automaticamente : <br>
<a href="%(url)s?key=%(key)s"> [<small> %(url)s?key=%(key)s </small>] </a></p><br>
<p>Se non sei tu ad aver richiesto la registrazione cancella pure questa email. Se lo desideri puoi eliminare l'account creato aprendo questo link : <br>
<a href="%(url)s?delete=%(key)s"> [<small> %(url)s?delete=%(key)s </small>] </a></p><br>
<p><small>Email generata automaticamente da Django. Non rispondere.</small></p>
"""

def signup(request):
	if request.user.is_active :
		return HttpResponseRedirect(reverse("login:index"))
	if request.user.is_authenticated() :
		return HttpResponseRedirect(reverse("login:signup_check"))
	if request.method == "GET" :
		return render(request,"mylogin/signup_form.html",{"reg_form":MyUserCreationForm()})
	# Inizializzo il Form e controlla i dati
	form = MyUserCreationForm(request.POST)
	if not form.is_valid() :
		return render(request,"mylogin/signup_form.html",{"reg_form":form})
	# Se l'IP ha gia' troppi utenti non verificati esco
	ip = request.META["REMOTE_ADDR"]
	unchecked_x_ip = UserVerificationKey.objects.filter(expire__gt=timezone.now(), ip = ip).count()
	if (unchecked_x_ip >= MAX_UNCHECKED_USER_X_IP):
		return HttpResponseRedirect(reverse("login:signup_check"))
	# Ottengo il modello dell'utente, lo disattivo, genero la chiave e salvo
	u = form.save(commit = False)
	u.is_active = False
	u.save()
	ukey = UserVerificationKey(user=u, ip=ip)
	ukey.save()
	# Invio la mail
	url = "https://" + request.META["HTTP_HOST"] + reverse("login:signup_check")
	address = u.email
	content = VERIFICATION_EMAIL_FORMAT%{"username":u.username, "key":ukey.key, "url":url, "host":request.META["HTTP_HOST"]}
	msg = EmailMessage( EMAIL_PREFIX + "Chiave verifica account", content, EMAIL_SENDER_ADDRESS, to=[address], bcc=[EMAIL_SENDER_ADDRESS])
	msg.content_subtype = "html"
	msg.send()
	if (ALLOW_WITHOUT_EMAIL):
		request.session["show_registration_key"]=ukey.key
	return HttpResponseRedirect(reverse("login:signup_check"))

def signup_check(request):
	if request.user.is_active :
		return HttpResponseRedirect(reverse("login:index"))
	check_key = request.GET.get("key","")
	to_delete = (not check_key)
	if to_delete :
		check_key = request.GET.get("delete","")
		to_delete = True
	context={"check_key":check_key, "to_delete":to_delete}
	if not check_key :
		if (ALLOW_WITHOUT_EMAIL):
			context["show_check_key"] = request.session.get("show_registration_key","")
		context["host"] = "http://" + request.META["HTTP_HOST"]
	else :
		try:
			ukey = UserVerificationKey.objects.select_related().get(expire__gt=timezone.now(), key=check_key)
		except (UserVerificationKey.DoesNotExist):
			context["is_key_valid"] = False
			context["error"] = "Codice chiave errata o scaduta"
		except (UserVerificationKey.MultipleObjectsReturned):
			context["is_key_valid"] = False
			context["error"] = "Codice chiave non univoca"
		else :
			context["is_key_valid"] = True
			user = ukey.user
			context["username"] = user.username
			if to_delete :
				user.delete()
			else :
				user.is_active=True
				user.save()
			ukey.delete()#Forse con OneToOneField potrebbe non essere necessario ?
	return render(request,"mylogin/signup_check.html",context)

def login_form(request):
	next_url = request.GET.get("next","")
	if next_url :
		request.session["next"] = next_url
	if request.user.is_authenticated() :
		return HttpResponseRedirect(next_url if next_url else reverse("login:index"))
	context = {}
	if ("error" in request.GET) :
		context["errors"] = request.session.pop("login_form_errors",{})
	return render(request,"mylogin/login_form.html", context)

def login(request):
	next_url=request.GET.get("next", request.session.pop("next", None))
	if request.user.is_authenticated() :
		return HttpResponseRedirect(next_url if next_url else reverse("login:index"))
	request.session["next"] = next_url
	request.session.pop("login_form_errors","")
	if not request.method == "POST" :
		return HttpResponseRedirect(reverse("login:dologin"))
	form = AuthenticationForm(request, request.POST)
	if not form.is_valid() :
		request.session["login_form_errors"] = {"non_field":form.non_field_errors(),"fields":[(x.name,x.errors) for x in form]}
		return HttpResponseRedirect(reverse("login:dologin")+"?error")
	u = form.get_user()
	messages.success(request, "Login affenuto con successo")
	u.backend = 'django.contrib.auth.backends.ModelBackend'
	django_login(request, u)
	if not u.is_active :
		HttpResponseRedirect(reverse("login:signup_check"))
	return HttpResponseRedirect(next_url if next_url else reverse("login:index"))

def logout(request):
	django_logout(request)
	return HttpResponseRedirect(reverse("login:index"))

mylogin/templates/mylogin/index.html
{% extends "mylogin/layout.html" %}
{% block content %}
<div class="jumbotron">{% if user.is_authenticated %}
	<h3>Dati utente « <b>{{ user.get_full_name }}</b> »</h3><br>
{% if user.is_active %}
	<table style="border:1px #000 dashed; width:100%; font-size:15px">
		<tr><td>Username </td><td>{{ user.username }}</td></tr>
		<tr><td>Email </td><td>{{ user.email }}</td></tr>
		<tr><td>Nome </td><td>{{ user.first_name }}</td></tr>
		<tr><td>Cognome </td><td>{{ user.last_name }}</td></tr>
	</table>
{% else %}
	<p>L'account non è attivo</p>
	<p>Controlla l'email</p>
{% endif %}{% else %}
	<p>Attualmente sei identificato come utente ospite anonimo</p>
	<a href="{% url 'login:login' %}" class="btn btn-default">Effettua l'accesso</a>
	<br>
{% endif %}</div>
{% endblock %}

mylogin/templates/mylogin/layout.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="Content-Type" content="text/html;charset=utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Gestione utente</title>
	<link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
	<style type="text/css">
		* { padding:0; margin:0; }
		body { background-color: #ddc !important; padding: 15px 0 0; }
		.navbar-header { float:initial;}
		.navbar { margin-left:10px; margin-right:10px;}
		footer { background-color:#bba; position: fixed; bottom: 0; width:100%; font-size:7pt; text-align:right; line-height:1.4;}
{% block style %}
{% endblock %}
	</style>
	<!--<link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap-theme.min.css' %}">-->
	<!--<script src="{% static 'jquery-2.1.1.min.js"></script>
	<script src="{% static 'bootstrap/js/bootstrap.min.js"></script>-->
</head>
<body>
<header class="navbar navbar-inverse navbar-default">
	<div class="navbar-header">
		<a class="navbar-brand" href="{% url 'login:index' %}">Gestione utente</a>
		<div class="btn-group pull-right" style="padding-right:15px;">
			{% if user.is_authenticated %}
			<a class="navbar-btn btn btn-success" href="{% url 'login:password_change' %}" title="Password change">Cambia password</a>
			<a class="navbar-btn btn btn-warning" href="{% url 'login:logout' %}" title="Log out">Esci</a>
			{% else %}
			<a class="navbar-btn btn btn-success" href="{% url 'login:signup' %}" title="Sign up">Registrati</a>
			<a class="navbar-btn btn btn-primary" href="{% url 'login:login' %}" title="Log in">Accedi</a>
			{% endif %}
		</div>
		<div class="btn-group pull-right" style="padding-right:15px;">
			<a class="navbar-btn btn btn-danger" href="/">Home</a>
		</div>
	</div>
</header>

<div class="container" style="font-size:80%;">
{% block content %}
{% endblock %}
</div>

<footer class="footer">
	<div class="container text-muted">
	</div>
</footer>
</body>
</html>

mylogin/templates/mylogin/login_form.html
{% extends "mylogin/layout.html" %}
{% block content %}
<div class="jumbotron">

<h2>Log in</h2>
<form class="signin-form" action="{% url 'login:login' %}" method="post">
	{% csrf_token %}
{% for error in errors.non_field %}
	<div class="alert alert-danger" role="alert">
		{{ error }}
	</div>
{% endfor %}{% for name,errors in errors.fields %}{% for error in errors %}
	<div class="alert alert-danger" role="alert">
		<strong>{{name}}</strong>: {{ error }}
	</div>
{% endfor %}{%endfor%}
	<label for="id_username" class="sr-only">Nome Utente:</label>
	<input maxlength="254" name="username" type="text" id="id_username" class="form-control" placeholder="Nome Utente" required autofocus>
	<label for="id_password" class="sr-only">Password</label>
	<input name="password" type="password" id="id_password" class="form-control" placeholder="Password" required>

	<div style="text-align:center; margin : 10pt 0 5pt 0;">
        <button class="btn btn-lg btn-primary btn-block" type="submit">Accedi</button>
	</div>
</form>
<p><br><a href={% url "login:password_reset" %}>Username o password dimenticati?</a></p>

</div>
{% endblock %}
  
{% block style %}
		.signin-form {
			text-align:center; font-size: 15px; max-width:450px; margin:0 auto; padding:10px;
		}
		.signin-form input {
			position: relative; width:100%; height: auto; box-sizing: border-box; padding: 10px; font-size: 16px;
		}
		.signin-form input[name="username"] { border-bottom-right-radius:0; border-bottom-left-radius:0; }
		.signin-form input[name="password"] { border-top-left-radius:0; border-top-right-radius:0; }
{% endblock %}

mylogin/templates/mylogin/password_change.html
{% extends "mylogin/layout.html" %}
{% block content %}

<div class="jumbotron">

<h2>Cambio password</h2>
<form action="{% url 'login:password_change' %}" method="post" class="change-form">
	{% csrf_token %}
	{% if form.non_field_errors %}<div class="alert alert-danger">{% for error in form.non_field_errors %}
		{{ error }}<br>
	{% endfor %}</div>{% endif %}
	<table style="width:100%">{% for field in form %}
		<tr><th>{{ field.label_tag }}</th><td>{{ field }}{% if field.help_text %}
			<div class="alert alert-info alert-small">{{ field.help_text}}</div>
		{% endif %}{% if field.errors %}
			<div class="alert alert-danger">{% for error in field.errors%}{{ error }}<br>{%endfor%}</div>
		{%endif%}</td></tr>
	{% endfor %}</table>
	<br>
	<div style="text-align:center; margin: 0 auto 0 auto; max-width:500px; padding: 10px 10px 5px;">
        <button class="btn btn-lg btn-success btn-block" type="submit">Conferma</button>
	</div>
</form>
</div>
{% endblock %}

{% block style %}
	.change-form {
		text-align:center; max-width:800px; margin:5px auto; padding:10px; font-size:13px;
	}
	.change-form input {
		width:100%;
	}
	.change-form th {
		width: 30%;
	}
	.change-form table .alert{
		margin-top 0; margin-bottom:3px; font-size: 11px;
	}
	.alert-small {
		margin: 0 0 0; padding: 2px; font-size:10px;
	}
{% endblock %}

mylogin/templates/mylogin/password_change_done.html
{% extends "mylogin/layout.html" %}
{% block content %}

<div class="jumbotron">

<h2>Cambio password completato</h2>
<div>
	<p class="small">La password &egrave; stata cambiata con successo.<br>
	<a href="{% url 'lupus:index' %}">Torna al sito</a></p>
</div>
</div>
{% endblock %}

{% block style %}

.jumbotron p.small {
	font-size: 18px;
}

{% endblock %}