lupus/urls.py
#from django.conf.urls import patterns, url, include
from django.conf.urls import url, include

from lupus import views
from lupus import gmviews
#from lupus import appviews

app_name = "lupus"

gm_patterns = [
	#SEZIONE GM
	url(r"^$", gmviews.GMView.as_view(), name="gm_index"),
	url(r"^(?P<id>\d+)$", gmviews.GMView.as_view(), name="gm_index_single"),
	#GESTIONE RUOLI
	url(r"^ruoli/(?P<match_id>\d*)$", gmviews.GMRolesView.as_view(), name="gm_assegnazione_ruoli"),
	url(r"^ruoli/users$", gmviews.gm_user_match, name="gm_user_match"),
	url(r"^ruoli/set$", gmviews.gm_set_role, name="gm_set_user_role"),
	url(r"^ruoli/setusers$", gmviews.gm_set_users_role, name="gm_set_users_role"),
	url(r"^ruoli/set/random$", gmviews.gm_set_role_random, name="gm_set_user_role_random"),
	#GESTIONE EVENTI
	url(r"^eventi/(?P<match_id>\d*)$", gmviews.GMEventsView.as_view(), name="gm_gestione_eventi"),
	url(r"^eventi/modifica$", gmviews.gm_edit_event, name="gm_modifica_evento"),
	url(r"^eventi/elimina$", gmviews.gm_del_event, name="gm_elimina_eveto"),
	url(r"^eventi/add", gmviews.gm_add_event, name="gm_aggiungi_evento"),
	#GESTIONE NOTE
	url(r"^note/(?P<match_id>\d*)$", gmviews.GMNotaView.as_view(), name="gm_gestione_note"),
	url(r"^note/modifica$", gmviews.gm_edit_nota, name="gm_modifica_nota"),
	url(r"^note/elimina$", gmviews.gm_del_nota, name="gm_elimina_nota"),
	url(r"^note/add", gmviews.gm_add_nota, name="gm_aggiungi_nota"),
	#GESTIONE AZIONI
	url(r"^azioni/(?P<match_id>\d*)$", gmviews.GMActionView.as_view(), name="gm_gestione_azioni"),
	url(r"^azioni/modifica$", gmviews.gm_edit_action, name="gm_modifica_azione"),
	url(r"^azioni/elimina$", gmviews.gm_del_action, name="gm_elimina_azione"),
	url(r"^azioni/add", gmviews.gm_add_action, name="gm_aggiungi_azione"),
	#GESTIONE STATI
	url(r"^status/(?P<match_id>\d*)$", gmviews.GMStatusView.as_view(), name="gm_gestione_status"),
	url(r"^status/modifica$", gmviews.gm_edit_status, name="gm_modifica_status"),
	url(r"^status/clear$", gmviews.gm_clear_status, name="gm_pulizia_status"),
	url(r"^status/random$", gmviews.gm_status_random, name="gm_assegnamento_status_random"),
	#GESTIONE GRUPPI
	url(r"^gruppi$", gmviews.GMGroupsView.as_view(), name="gm_gestione_gruppi"),
	url(r"^gruppi/add$", gmviews.gm_add_group, name="gm_aggiungi_gruppo"),
	url(r"^gruppi/edit$", gmviews.gm_edit_group, name="gm_modifica_gruppo"),
	url(r"^gruppi/del$", gmviews.gm_del_group, name="gm_elimina_gruppo"),
	#GESTIONE MATCH
	url(r"^match$", gmviews.GMMatchView.as_view(), name="gm_gestione_match"),
	url(r"^match/add$", gmviews.gm_add_match, name="gm_aggiungi_match"),
	url(r"^match/edit$", gmviews.gm_edit_match, name="gm_modifica_match"),
	url(r"^match/del$", gmviews.gm_del_match, name="gm_elimina_match"),
	url(r"^match/deactivate$", gmviews.gm_deactivate_users_match, name="gm_disattiva_utenti_match"),
	#GESTIONE VOTAZIONI
	url(r"^votazioni/(?P<match_id>\d*)$", gmviews.GMVotiView.as_view(), name="gm_gestione_voti"),
	url(r"^votazioni/modifica$", gmviews.gm_edit_voto, name="gm_modifica_voto"),
	url(r"^votazioni/elimina$", gmviews.gm_del_voto, name="gm_elimina_voto"),
	url(r"^votazioni/add$", gmviews.gm_add_voto, name="gm_aggiungi_voto"),
	#GESTIONE NOTTE E LINCIAGGIO
	url(r"^notte/(?P<match_id>\d*)$", gmviews.GMValView.as_view(), name="gm_gestione_notte", kwargs={"flags": 2}),
	url(r"^notte/confirm$", gmviews.GMValConfirmView.as_view(), name="gm_conferma_notte"),
	url(r"^notte/do$", gmviews.GMValDoPostView.as_view(), name="gm_esegui_notte"),
	#url(r"^notte/do$", gmviews.gm_val_do, name="gm_esegui_notte"),
	url(r"^linciaggio/(?P<match_id>\d*)$", gmviews.GMValView.as_view(), name="gm_linciaggio", kwargs={"flags": 1}),
	url(r"^linciaggio/confirm$", gmviews.GMValConfirmView.as_view(), name="gm_conferma_linciaggio"),
	url(r"^linciaggio/do$", gmviews.GMValDoPostView.as_view(), name="gm_esegui_linciaggio"),
	#url(r"^linciaggio/do$", gmviews.gm_val_do, name="gm_esegui_linciaggio"),
	#CAMBIO PROFILO
	url(r"^profile$", gmviews.GMChangeProfileView.as_view(), name="gm_setprofile"),
	#GESTIONE FINE MATCH
	url(r"^end/(?P<match_id>\d*)$", gmviews.GMEndMatch.as_view(), name="gm_end_match"),
	#GESTIONE GM
	url(r"^staff$", gmviews.GMStaffView.as_view(), name="gm_staff"),
	url(r"^staff/add$", gmviews.gm_add_staff, name="gm_staff_add"),
	url(r"^su/add$", gmviews.gm_add_su, name="gm_su_add"),
	url(r"^su/del/(?P<id>\d+)$", gmviews.gm_del_su, name="gm_su_elimina"),
	#GESTIONE ISCRITTI
	url(r"^iscritti/(?P<match_id>\d+)$", gmviews.GMIscrittiView.as_view(), name="gm_gestione_iscritti"),
	url(r"^iscritti/edit$", gmviews.gm_edit_iscritto, name="gm_modifica_iscritto"),
	url(r"^iscritti/del$", gmviews.gm_del_iscritto, name="gm_elimina_iscritto")
]



urlpatterns = [
	# INDICE E GIORNALE
	url(r"^$", views.Index.as_view(), name ="index"),
	url(r"^index$", views.Index.as_view()),
	url(r"^giornale(?P<match_id>\d+)$", views.GiornaleView.as_view(), name="giornale"),
	url(r"^giornale/pdf(?P<match_id>\d+)$", views.notImplemented.as_view(), name ="giornale_pdf"),
	# REGOLAMENTO
	url(r"^regolamento$", views.RegView.as_view(), name ="regolamento"),
	url(r"^regolamento/online$", views.RegOnlineView.as_view(), name ="regolamento_online"),
	# GESTIONE MATCH
	url(r"^game$", views.GameView.as_view(), name ="gioco"),
	url(r"^game/leave$", views.GameLeaveView.as_view(), name ="gioco_leave"),
	url(r"^game/askleave$", views.GameAskLeaveView.as_view(), name ="gioco_askleave"),
	# GESTIONE PROFILO
	url(r"^profile$", views.ProfileView.as_view(), name ="profile"),
	url(r"^profile/make$", views.ProfileMakeView.as_view(), name ="profile_make"),
	url(r"^profile/(?P<user_id>\d+)$", views.ProfileOtherView.as_view(), name="profile_other"),
	# RIASSUNTO STATUS
	url(r"^status$", views.StatusView.as_view(), name ="status"),
	url(r"^status/postaction$", views.StatusActionView.as_view(), name ="status_action"),
	# VILLAGGIO E VOTAZIONI
	url(r"^villaggio/pastsindaco", views.VotazioniPassateSindacoView.as_view(), name ="villaggio_pastsindaco"),
	url(r"^villaggio/past", views.VotazioniPassateView.as_view(), name ="villaggio_past"),
	#url(r"^villaggio/postvoto(?P<flag_id>\d{1})_(?P<utente_id>\d+)$", views.VillaggioPostVotoView.as_view(), name ="villaggio_postvoto"),
	url(r"^villaggio/postvoto$", views.VillaggioPostFormVotoView.as_view(), name ="villaggio_postvoto"),
	url(r"^villaggio", views.VillaggioView.as_view(), name ="villaggio"),
	# PROPRIO GRUPPO E AZIONI NOTTURNE
	url(r"^gruppo$", views.GruppoView.as_view(), name ="gruppo"),
	url(r"^gruppo/azione$", views.GruppoAzioneView.as_view(), name ="gruppo_azione"),
	# CHAT DI GRUPPO
	url(r"^gruppo/postmsg$", views.gruppo_postmsg, name ="gruppo_postmsg"),
	url(r"^gruppo/getmsg(?P<isvillaggio>\d{1})_(?P<first_id>\d+)to(?P<last_id>\d+)$", views.gruppo_getmsg, name ="gruppo_getmsg"),
	# RIASSUNTO
	url(r"^summary$", views.SummaryCurrentView.as_view(), name ="summary_current"),
	url(r"^summary/match(?P<match_id>\d+)$", views.SummaryView.as_view(), name ="summary"),
	url(r"^summary/history(?P<match_id>\d+)$", views.SummaryFullView.as_view(), name ="summary_full"),
	url(r"^summary/pdf(?P<match_id>\d+)$", views.notImplemented.as_view(), name ="summary_pdf"),
	
	url(r"^IE.html$", views.IEwarningView.as_view(), name="IEwarning"),
	
	# GAME MASTER
	url(r'^gm/', include((gm_patterns,""))),
	
	# PROCEDURE AUTOMATICHE
	url(r'^auto/', include(
		([
			url(r"^giorno_all$", views.esegui_giorno_all_view, name ="giorno_all"),
			url(r"^notte_all$", views.esegui_notte_all_view, name ="notte_all"),
			url(r"^vittoria_all$", views.esegui_vittoria_all_view, name ="vittoria_all")
		],"auto")
	,namespace="auto")),
]

lupusrealtime/urls.py
from django.conf.urls import include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = [
    # Examples:
    # url(r'^$', 'lupusrealtime.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^', include('lupus.urls', namespace="lupus")),
    url(r'^auth/', include("mylogin.urls", namespace="login")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
]

mylogin/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from mylogin import views

app_name = "login"

urlpatterns = [
	url(r"^$", views.index, name ="index"),
	url(r"^login/$", views.login, name ="login"),
	url(r"^logout/$", views.logout, name ="logout"),
	url(r"^dologin/$", views.login_form, name ="dologin"),
	url(r"^signup/$", views.signup, name ="signup"),
	url(r"^check/$", views.signup_check, name ="signup_check"),
	url(r"^password/reset$", auth_views.password_reset, {"template_name": "mylogin/password_reset.html", "password_reset_form": views.MyPasswordResetForm, "post_reset_redirect": "login:password_reset_done"}, name="password_reset"),
	url(r"^password/reset/sent$", auth_views.password_reset_done, {"template_name": "mylogin/password_reset_done.html"}, name="password_reset_done"),
	url(r"^password/reset/confirm/uid=(?P<uidb64>[0-9A-Za-z_\-]+)&token=(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})$", auth_views.password_reset_confirm, {"template_name": "mylogin/password_reset_confirm.html", "post_reset_redirect": "login:password_reset_complete"}, name="password_reset_confirm"),
	url(r"^password/reset/done$", auth_views.password_reset_complete, {"template_name": "mylogin/password_reset_complete.html"}, name="password_reset_complete"),
	url(r"^password/change$", auth_views.password_change, {"template_name": "mylogin/password_change.html", "post_change_redirect": "login:password_change_done"}, name="password_change"),
	url(r"password/change/done$", auth_views.password_change_done, {"template_name": "mylogin/password_change_done.html"}, name="password_change_done"),
]

lupus/models.py
# -*- encoding: utf8 -*-
from django.db import models
from django.contrib.auth.models import User

from lupusrealtime.settings import *
#from lupus.setting import GAMETIME_NIGHTSTART, *
from lupus.setting import *

from lupus.time import localnow
from django.utils.timezone import timedelta

from random import randint

class Match(models.Model) :
	class Meta:
		verbose_name_plural = "Matchs"
	def __init__(self, *args, **kwargs) :
		if not ("startdate" in kwargs):
			kwargs["startdate"]=localnow().date()+timedelta(days=21)
		if not ("regenddate" in kwargs) :
			kwargs["regenddate"]=localnow().date()+timedelta(days=20)
		super(Match, self).__init__(*args, **kwargs)
	def __bool__(self):
		return bool(self.id)
	def __int__(self) :
		return self.id
	def __str__(self):
		return self.nome
	nome = models.CharField(max_length=30)
	startdate = models.DateField("Start Date")
	regenddate = models.DateField("Registration End Date", blank=True)
	enddate = models.DateField("End Date", null=True, blank=True)
	villaggio = models.OneToOneField("Gruppo", related_name="villaggio", related_query_name="villaggio", null=True, on_delete=models.CASCADE)
	active = models.BooleanField("active", default = False)
	winner = models.CharField(max_length=1, choices=FAZIONI_CHOICES, default="", blank=True)
	gm = models.ForeignKey(User, null=True, related_name="gm_set", related_query_name="gm", on_delete=models.CASCADE)
	def isStarted(self, now=localnow()):
		return (self.active) and (self.winner == "") and ((self.startdate < now.date())or((now.date() == self.startdate)and(now.time()>=GAMETIME_NIGHTSTART)))
	def isRegistrable(self, now=localnow()):
		return (self.active) and (self.regenddate >= now.date())

class Gruppo(models.Model) :
	class Meta:
		verbose_name_plural = "Gruppi"
	def __str__(self):
		return str(self.id)+":"+self.name
	def __bool__(self):
		return bool(self.id)
	def __bool__(self):
		return bool(self.id)
	name = models.CharField(max_length=30)
	ruolo = models.CharField(max_length=4, choices=RUOLI_CHOICES, default="CON")
	match = models.ForeignKey(Match, on_delete=models.CASCADE)

class Utente(models.Model) :
	class Meta:
		verbose_name = "Profilo"
		verbose_name_plural = "Profili"
	def __bool__(self):
		return bool(self.id)
	def __str__(self):
		try :
			nome = self.user.get_full_name()
		except (User.DoesNotExist):
			nome = "##NESSUNO##"
		return str(self.id)+"(%s):"%self.nome+nome
	nome = models.CharField(max_length=30)
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	ruolo = models.CharField(max_length=4, choices=RUOLI_CHOICES, default="CON", null=True)
	stato = models.SmallIntegerField(default=0)
	gruppo = models.ForeignKey(Gruppo, null=True, blank=True, on_delete=models.CASCADE)
	genere = models.SmallIntegerField(choices=((1, "Maschio"),(2, "Femmina")))
	match = models.ForeignKey(Match, null=True, on_delete=models.CASCADE)
	active = models.BooleanField("active", default=False)
	def get_ruolo(self):
		return RUOLI[self.ruolo]

class Votazione(models.Model) :
	class Meta:
		verbose_name_plural = "Votazioni"
	def __str__(self):
		return "%d#%d,%s,U%d"%(self.id,self.flags,str(self.date),self.utente.id)
	utente = models.ForeignKey(Utente, on_delete=models.CASCADE)
	flags = models.SmallIntegerField(default=1)
	count = models.SmallIntegerField(default=0)
	date = models.DateField("date")

class Voto(models.Model) :
	class Meta:
		verbose_name_plural = "Voti"
	def __str__(self):
		return "%d#%d,%s,V%d"%(self.id,self.flags,str(self.time),self.votante.id)
	time = models.DateField("time")
	votante = models.ForeignKey(Utente, on_delete=models.CASCADE)
	flags = models.SmallIntegerField(default=1)
	risultato = models.ForeignKey(Votazione, on_delete=models.CASCADE)

class Azioni(models.Model) :
	class Meta:
		verbose_name_plural = "Azioni"
	def __str__(self):
		return "%s#%s,A%d"%(str(self.id) if self.id else "NONE",str(self.time),self.agente.id)
	agente = models.ForeignKey(Utente, related_name="azioni_set", related_query_name="azioni", on_delete=models.CASCADE)
	time = models.DateField("time")
	bersaglio = models.ForeignKey(Utente, related_name="subite_set", related_query_name="subite", on_delete=models.CASCADE)

class Messaggio(models.Model) :
	class Meta:
		verbose_name = "Messaggio chat"
		verbose_name_plural = "Messaggi chat"
	def __str__(self):
		return "%d:U%d,G%d"%(self.id,self.utente.id,self.gruppo.id)
	time = models.DateTimeField("time")
	text = models.CharField(max_length=200)
	utente = models.ForeignKey(Utente, on_delete=models.CASCADE)
	gruppo = models.ForeignKey(Gruppo, on_delete=models.CASCADE)

class Eventi(models.Model) :
	class Meta:
		verbose_name_plural = "Eventi"
	#def __str__(self):
	#	return "%d:U%d,G%d"%(self.id,self.utente.id,self.gruppo.id)
	def __init__(self, *args, **kwargs) :
		if (not "scena" in kwargs) and (kwargs.get("random_scene",False)) :
			maxs = EVENTI[kwargs.get("flags",0)]["scenes"]
			if maxs : 
				kwargs["scena"]=randint(1,maxs)
			del kwargs["random_scene"]
		super(Eventi, self).__init__(*args, **kwargs)
	def __str__(self):
		return "<Evento %s:%s>"%(str(self.id), self.get_flags_display())
	date = models.DateField("date")
	flags = models.SmallIntegerField("flags", default=1, choices=EVENTI_CHOICES)
	scena = models.SmallIntegerField("scena", default=0)
	utente = models.ForeignKey(Utente, on_delete=models.CASCADE)
	def get_human_name(self):
		return EVENTI[self.flags]["Help"]
	def get_dict(self):
		return EVENTI[self.flags]
	def get_data(self):
		pass

class Status(models.Model) :
	class Meta:
		verbose_name_plural = "Status"
	def __str__(self):
		return "<Status U%s, %d>"%(str(self.utente_id),self.flags)
	utente = models.ForeignKey(Utente, on_delete=models.CASCADE)
	flags = models.SmallIntegerField("flags", choices=STATUS_CHOICES)
	opt = models.IntegerField("opt", default=0)
	def get_dict(self):
		return STATUS_FLAG[self.flags]
	#def get_data(self):
	#	return STATUS_DATA[self.get_dict()["ID"]]
	def get_ID(self):
		return self.get_dict()["ID"]

class Nota(models.Model) :
	class Meta:
		verbose_name_plural = "Note"
	def __str__(self):
		return "<Nota #%id %s %s>"%(self.id, self.flags, str(self.time))
	utente1 = models.ForeignKey(Utente, related_name="nota1_set", related_query_name="nota1", on_delete=models.CASCADE)
	utente2 = models.ForeignKey(Utente, related_name="nota2_set", related_query_name="nota2", null=True, blank=True, on_delete=models.CASCADE)
	time = models.DateField("time")
	flags = models.CharField("flags", max_length=4, choices=NOTE_CHOICES)
	opt =  models.IntegerField("opt", default=0, blank=True)
	text =  models.CharField("text", default="", max_length=50, blank=True)
	def get_dict(self):
		return NOTE[self.flags]

class LogGestione(models.Model) :
	class Meta:
		verbose_name_plural = "LogGestioni"
	def __init__(self, *args, **kwargs):
		kwargs.setdefault("time", localnow())
		super(LogGestione, self).__init__(*args, **kwargs)
	def __str__(self):
		return "Log%d for %s in %s"%(self.id,self.get_flag_display(),str(self.date))
	flag = models.SmallIntegerField("flag", choices=((1,"tramonto"),(2,"notte")))
	time = models.DateTimeField("time")
	date = models.DateField("date")
	automatico = models.BooleanField("auto", default=False)
	match  = models.ForeignKey(Match, on_delete=models.CASCADE)
	azioni = models.CharField("azioni", max_length=1000)

class LogAccesso(models.Model) :
	class Meta:
		verbose_name_plural = "LogAccessi"
	def __str__(self):
		return "Logaccesso utente %d il %s"%(self.utente_id,str(self.date))
	timeflag = models.SmallIntegerField("timeflag", choices=((1,"notte"),(2,"giorno")))
	date = models.DateField("date") #il giorno di gioco
	utente = models.ForeignKey(Utente, on_delete=models.SET_NULL, null=True)

lupus/templates/lupus/ask_leave.html
{% extends layout|default:"lupus/layout.html" %}
{% load static %}

{% block content %}
<div class="lp-panel lp-panel-danger">
	<h4>Attenzione !! </h4>
	<p>Hai appena richiesto di abbandonare il match "<i>{{ nome }}</i>" a cui sei iscritto.</p>
	<p>Se abbandoni ora questo match potresti causare anomalie nel gioco e disagi agli altri giocatori. Pensaci bene!<br>
	Se abbandonerai la partita non sarà più possibli ritornarci (a meno di non contattare l'amministratore). Inoltre il tuo personagggio diventerà vecchio.</p>
	<p>Cosa hai deciso ?</p>
    <div class="btn-group"><a href="{% url 'lupus:gioco' %}" class="btn">Ho cliccato Abbandona per sbaglio</a><small><a href="{% url 'lupus:gioco_leave' %}?confirm=true" class="btn">Sono cattivo e abbandono il match</a></small><br clear=both></div>	
</div>
{% endblock %}

{% block style %}
{% endblock %}

lupus/templates/lupus/gm_ask_valutazione.html
{% extends layout|default:"lupus/layout_gm.html" %}
{% load filter %}

{% block content %}
<div class="lp-panel lp-panel-info">
	<h3>Conferma valutazione {% ifequal flags 2 %}notte{% else %}votazioni{% endifequal %}</h3>
</div>
<div class="lp-panel">
	{% if morti %}
	<h4>Morti:</h4>
		<ul>
			{% for u in morti %}
				<li>{{u.nome}}</li>
			{% endfor %}
		</ul>
		<br />
	{% endif %}
	{% if risorti %}
		<h4>Risorti:</h4>
		<ul>
			{% for u in risorti %}
				<li>{{u.nome}}</li>
			{% endfor %}
		</ul>
		<br />
	{% endif %}
	{% if eventi %}
		<h4>Eventi che verranno aggiunti:</h4>
		<table class="nicehover">
			<thead>
				<tr>
					<td>Utente</td>
					<td>Flags</td>
					<td>Scena</td>
				</tr>
			</thead>
			<tbody>
				{% for e in eventi %}
					<tr>
						<td>{{users|dictget:e.utente}}</td>
						<td>{{eventi_flags|dictget:e.flags|dictget:"Help"}}</td>
						<td>{% if e.scena %}{{e.scena}}{% endif %}</td>
					</tr>
				{% endfor %}
			</tbody>
		</table>
		<br />
	{% endif %}
	{% if note %}
		<h4>Note che verranno aggiunte:</h4>
		<table class="nicehover">
			<thead>
				<tr>
					<td>Utente 1</td>
					<td>Flags</td>
					<td>Utente 2</td>
					<td>Opt</td>
					<td>Text</td>
				</tr>
			</thead>
			<tbody>
				{% for n in note %}
					<tr>
						<td>{{users|dictget:n.utente1}}</td>
						<td>{{note_flags|dictget:n.flags|dictget:"help"}}</td>
						<td>{% if n.utente2 %}{{users|dictget:n.utente2}}{% endif %}</td>
						<td>{% if n.opt %}{{n.opt}}{% endif %}</td>
						<td>{{n.text}}</td>
					</tr>
				{% endfor %}
			</tbody>
		</table>
		<br />
	{% endif %}
	{% if status %}
		<h4>Status che verranno aggiunti:</h4>
		<table class="nicehover">
			<thead>
				<tr>
					<td>Utente</td>
					<td>Flags</td>
					<td>Opt</td>
				</tr>
			</thead>
			<tbody>
				{% for s in status %}
					<tr>
						<td>{{users|dictget:s.utente}}</td>
						<td>{{status_flags|dictget:s.flags|dictget:"Nome"}}</td>
						<td>{% if s.opt %}{{s.opt}}{% endif %}</td>
					</tr>
				{% endfor %}
			</tbody>
		</table>
		<br />
	{% endif %}
	<div>
		<form method="POST" action="{% ifequal flags 2 %}{% url 'lupus:gm_esegui_notte' %}{% else %}{% url 'lupus:gm_esegui_linciaggio' %}{% endifequal %}">
			{% csrf_token %}
			<input type="hidden" name="confirm" value="true"/>
			<input type="hidden" name="mid" value="{{mid}}" />
			<div style="float:left; width:50%; text-align: center;">
			<input type="submit" class="btn" value="Conferma"/>
			</div>
			<div style="float:left; width:50%; text-align: center;">
			<a href="{% ifequal flags 2 %}{% url 'lupus:gm_gestione_notte' mid %}{% else %}{% url 'lupus:gm_linciaggio' mid %}{% endifequal %}" class="btn">Annulla</a>
			</div>
			<div style="clear:both;"></div>
		</form>
	</div>
</div>
{% endblock %}

{% block style %}
td {
	max-width: 250px;
	word-wrap: break-word
}
{% endblock %}

lupus/templates/lupus/index.html
{% extends layout|default:"lupus/layout.html" %}
{% block content %}

<div class="lp-panel lp-panel-success">
    <h3>Lupus Real Time</h3>
    <p>Questo sito è un'applicazione web finalizzata al gioco di Lupus Real Time, un RPG ispirato a giochi come Lupus e Mafia.</p>
    Puoi leggere e/o scaricare <a href="{% url 'lupus:regolamento' %}">il regolamento nella pagina dedicata</a></p>
    <p>Il gioco è diventente e ci si prende in fretta la mano, sebbene inizialmente possa essere un poco complicato.
    Per i sani di mente non richiede molto tempo.</p>
</div>
<div class="lp-panel lp-panel-info">
    <h4>Per giocare</h4>
    <p>Se vuoi giocare devi iscriverti ad un match ed aspettare l'inizio</p>
    {% if nuovi %}
    <p>Ci sono {{ nuovi }} match con le iscrizioni aperte.
    Per iscriverti devi <a href="{% url 'login:login' %}?next={% url 'lupus:gioco' %}">accedere o registrare un account</a> ed andare alla sezione "Gioco".</p>
    {% else %}
    <p>Ora non ci sono match con le iscrizioni aperte. Puoi comunque già <a href="{% url 'login:login' %}">registrare un account</a>.</p>
    {% endif %}
</div>
<div class="lp-panel lp-panel-warning">
	<h4>Match in corso e finite da poco</h4>
	<p>Anche senza fare il login puoi vedere le home page delle partite in corso.</p>
	<p>Nella <a href="{% url 'lupus:gioco' %}">sezione "Gioco"</a> puoi vedere un elenco di tutti match.</p>
	{% if recenti %}
	<br><p>Gli ultime partite terminate si sono concluse così:<br style="clear:both;"></p>
	<ul style="padding-top:10px;">{% for id,nome,fine in recenti %}
		<li><a href="{% url 'lupus:summary' id %}">Nel match <b>{{nome}}</b> {{fine}}</a></li>
	{% endfor %}</ul>
	{% endif %}
</div>
<div class="lp-panel lp-panel-danger">
	<h4>Collaborazioni, consigli e gamemaster</h4>
	<p>Vuoi proporre un match e conosci già chi può essere il gamemaster? Vuoi darci una mano? Hai consigli od osservazioni ?<br>
	Allora non esitare a <a href="mailto:{{ email }}"><span>contattarci</span></a></p>
</div>
{% endblock %}